- shell:
    - description: Add docker repository
      command: if [ ! -e .lock/docker ]; then
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add - &&
        sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu  $(lsb_release -cs)  stable" &&
        sudo apt update &&
        touch .lock/docker;
        fi
      quiet: true

- aptget:
    - docker-ce
    - docker-ce-cli
    - containerd.io

- shell:
    - description: Install docker-compose
      command: if [ ! -e .lock/docker-compose ]; then
        curl -L "https://github.com/docker/compose/releases/download/1.24.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose &&
        chmod +x /usr/local/bin/docker-compose
        touch .lock/docker-compose;
        fi
      quiet: true
