- sudo:
    - aptget:
        - flatpak
        - gnome-software-plugin-flatpak
- shell:
    - description: Add the Flathub repository
      command: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo     
      quiet: true
