- shell:
    - description: Add gimp repository
      command: if [ ! -e .lock/gimp ]; then
        sudo add-apt-repository ppa:otto-kesselgulasch/gimp &&
        sudo apt-get update;
        fi
      quiet: true
    - description: Install ferdi
      command: if [ ! -e .lock/ferdi ]; then
        wget https://github.com/getferdi/ferdi/releases/download/v5.4.3/ferdi_5.4.3_amd64.deb &&
        sudo apt install ./ferdi_5.4.3_amd64.deb &&
        rm ferdi_5.4.3_amd64.deb
        sudo -u $SUDO_USER touch .lock/ferdi;
        fi
      quiet: true

- aptget:
    - gimp
    - cheese

- shell:
    - snap install vlc
