- shell:
    - description: Add node repository
      command: if [ ! -e .lock/node ]; then
        curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash - &&
        touch .lock/node;
        fi
      quiet: true
    - description: Add yarn repository
      command: if [ ! -e .lock/yarn ]; then
        curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add - &&
        echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list &&
        touch .lock/yarn;
        fi
      quiet: true

- aptget:
    - nodejs
    - yarn
