- shell:
    - description: Add ppa repository
      command: if [ ! -e .lock/php ]; then
        add-apt-repository ppa:ondrej/php &&
        sudo -u $SUDO_USER touch .lock/php;
        fi
      quiet: true

- aptget:
    - php7.1
    - php7.1-bcmath
    - php7.1-cli
    - php7.1-common
    - php7.1-curl
    - php7.1-fpm
    - php7.1-gd
    - php7.1-json
    - php7.1-mbstring
    - php7.1-mysql
    - php7.1-opcache
    - php7.1-readline
    - php7.1-xml
    - php7.1-zip
    - php7.1-tidy
    - php7.1-intl
    - php7.1-soap
    # - php7.2
    # - php7.2-bcmath
    # - php7.2-cli
    # - php7.2-common
    # - php7.2-curl
    # - php7.2-fpm
    # - php7.2-gd
    # - php7.2-json
    # - php7.2-mbstring
    # - php7.2-mysql
    # - php7.2-opcache
    # - php7.2-readline
    # - php7.2-xml
    # - php7.2-zip
    # - php7.2-tidy
    # - php7.2-intl
    # - php7.2-soap
    - php7.3
    - php7.3-bcmath
    - php7.3-cli
    - php7.3-common
    - php7.3-curl
    - php7.3-fpm
    - php7.3-gd
    - php7.3-json
    - php7.3-mbstring
    - php7.3-mysql
    - php7.3-opcache
    - php7.3-readline
    - php7.3-xml
    - php7.3-zip
    - php7.3-tidy
    - php7.3-intl
    - php7.3-soap
    # - php7.4
    # - php7.4-bcmath
    # - php7.4-cli
    # - php7.4-common
    # - php7.4-curl
    # - php7.4-fpm
    # - php7.4-gd
    # - php7.4-json
    # - php7.4-mbstring
    # - php7.4-mysql
    # - php7.4-opcache
    # - php7.4-readline
    # - php7.4-xml
    # - php7.4-zip
    # - php7.4-tidy
    # - php7.4-intl
    # - php7.4-soap

- shell:
    - description: Install composer
      command: if [ ! -e .lock/composer ]; then
        php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" &&
        sudo php composer-setup.php --install-dir=/usr/local/bin --filename=composer &&
        rm composer-setup.php &&
        sudo -u $SUDO_USER touch .lock/composer;
        fi
      quiet: true
